value: fix windows build
error C2968: 'Value<double>': recursive alias declaration

Due to use of Value within definition of RawValue; switched these to
use the local definition of ptr (of which Value is an alias)